version: '2.1'
services:
  mariadb:
    image: 'docker.io/bitnami/mariadb:10.3-debian-10'
    environment:
      - MARIADB_USER
      - MARIADB_DATABASE
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    # volumes:
      # - 'mariadb_data:/bitnami/mariadb'
      # - './data/mantidwiki-full-backup-2021-03-11.sql.gz:/docker-entrypoint-initdb.d/initdb.sql.gz'
    # healthcheck:
    #     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
    #     timeout: 5s
    #     retries: 3

  mediawiki:
    image: 'bitnami/mediawiki:1.35.1-debian-10-r69'
    ports:
      - '80:8080'
      - '443:8443'
    environment:
      - SERVER_HOST=localhost
      - SERVER_PORT=8080
      - MEDIAWIKI_SKIP_BOOTSTRAP=${MEDIAWIKI_SKIP_BOOTSTRAP:-no}
      - MEDIAWIKI_DATABASE_HOST=mariadb
      - MEDIAWIKI_DATABASE_PORT_NUMBER=3306
      - MEDIAWIKI_DATABASE_NAME
      - MEDIAWIKI_DATABASE_USER
      - MEDIAWIKI_DATABASE_PASSWORD
    # volumes:
      # - 'mediawiki_images:/bitnami/mediawiki/images'
      # - './data/mantidwiki-images-2021-03-11.tar.gz:/docker-entrypoint-init.d/images.tar.gz'
    depends_on:
      - mariadb
      # depends_on:
    #   mariadb:
    #     condition: service_healthy
# volumes:
   #   mariadb_data:
#     driver: local
#   mediawiki_images:
#     driver: local
