name: Close issues related to a merged pull request based on a non-default branch.

on:
  pull_request:
    types: [closed]
    branches:
      - release-next

jobs:
  closeIssueOnPrMergeTrigger:

    runs-on: ubuntu-latest

    steps:
      - name: Closes issues related to a merged pull request.
        uses: martyngigg/gha-mjolnir@v1.0.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
