name: 'Check for merge conflicts'
on:
  push:
    branches:
      - main
jobs:
  label-conflicts:
    runs-on: ubuntu-latest
    steps:
      - uses: prince-chrismc/label-merge-conflicts-action@v1
        with:
          conflict_label_name: "Has Conflicts"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # These are optional incase you need to adjust for the limitations described below
          max_retries: 5
          wait_ms: 15000
          detect_merge_changes: false
          conflict_comment: ":wave: Hi, @${author},\n\nI detected conflicts against the base branch. You'll want rebase :arrows_counterclockwise: your branch with upstream!"

